### ISSUE TITLE
Loosen bleak dependency

### ISSUE THREAD

**Issue by t3chguy** [builder555/pinecil_lib#1]
HomeAssistant updated to 0.22.1 and `^0.21.1` is no longer compatible with that because semver handles `0.x.y` as unstable and thus applies a narrower range.

![image](https://github.com/builder555/pinecil_lib/assets/2403652/053c9de7-17f4-495a-be89-3a36d07deac0)

`>=0.21.1,<1.0.0` would be great.

Thanks in advance

Related https://github.com/t3chguy/pinecil_ble/issues/7

**Comment by builder555** [comment]
this ought to do it: 1e18398d2fd8c1440b7a6fd45f37e6805bc4c465

**Comment by t3chguy** [comment]
Appreciate your prompt solution @builder555 - could I ask for a pip release 😇 

![image](https://github.com/builder555/pinecil_lib/assets/2403652/c83177dc-3abc-404c-a529-5b0389c143da)

You are way ahead of me

**Comment by builder555** [comment]
> You are way ahead of me

am not, but gh actions are ;)
